# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
print(s.split(' '))

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 FIVES:")
print(array)

An array of 10 FIVES:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
data = [{'a': 1, 'b': 2 },
        {'a': 10, 'b': 20},
        {'a':100,'b':200}]
  
df = pd.DataFrame(data)
df

a    b
0    1    2
1   10   20
2  100  200

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
date_generated = pd.date_range(start='01/01/2023', end='10/02/2023',periods=41)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '07-01-2023', '14-01-2023', '21-01-2023', '28-01-2023',
       '04-02-2023', '11-02-2023', '17-02-2023', '24-02-2023', '03-03-2023',
       '10-03-2023', '17-03-2023', '24-03-2023', '31-03-2023', '06-04-2023',
       '13-04-2023', '20-04-2023', '27-04-2023', '04-05-2023', '11-05-2023',
       '18-05-2023', '24-05-2023', '31-05-2023', '07-06-2023', '14-06-2023',
       '21-06-2023', '28-06-2023', '04-07-2023', '11-07-2023', '18-07-2023',
       '25-07-2023', '01-08-2023', '08-08-2023', '15-08-2023', '21-08-2023',
       '28-08-2023', '04-09-2023', '11-09-2023', '18-09-2023', '25-09-2023',
       '02-10-2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =[' w1', 'w2 ', 'w3']) 
print(df)

    w1  w2   w3
0    1  aaa  22
1    2  bbb  25
2    3  ccc  24
